package com.example.myvirtusizetestapp.network.models.request

data class Criteria(
    val bodyData: BodyData,
    val bottomsFit: String,
    val bottomsLength: String,
    val bottomsType: String,
    val brand: String,
    val category: String,
    val color: String,
    val fit: String,
    val materials: Materials,
    val measurements: Measurements,
    val necklineType: String,
    val occasion: String,
    val overclothesClosure: String,
    val overclothesNecklineType: String,
    val overclothesType: String,
    val pattern: String,
    val productName: String,
    val search: String,
    val skirtLength: String,
    val skirtType: String,
    val sleeveLength: String,
    val sleeveType: String,
    val style: String,
    val tankType: String,
    val topsFit: String,
    val topsLength: String,
    val type: String,
    val waistType: String
)