package com.example.myvirtusizetestapp.network.models.request

data class CustomEsWeights(
    val bottomsFit: Int,
    val bottomsLength: Int,
    val bottomsType: Int,
    val brand: Int,
    val category: Int,
    val color: Int,
    val fit: Int,
    val fitScore: Int,
    val material: Int,
    val necklineType: Int,
    val occasion: Int,
    val overclothesClosure: Int,
    val overclothesNecklineType: Int,
    val overclothesType: Int,
    val pattern: Int,
    val productName: Int,
    val skirtLength: Int,
    val skirtType: Int,
    val sleeveLength: Int,
    val sleeveType: Int,
    val style: Int,
    val tankType: Int,
    val topsFit: Int,
    val topsLength: Int,
    val type: Int,
    val waistType: Int
)